# Generated by Django 2.2.9 on 2022-03-09 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_auto_20220309_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['pk'], 'verbose_name': 'Сообщество',
                     'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Пост',
                     'verbose_name_plural': 'Посты'},
        ),
    ]
